Added readme file with eslint fixes
sanjayadesilva123321/sample-app-frontend pull request #3
Opened 2023-11-24 06:19 UTC by sanjayadesilva123321

2023-11-24 07:35 UTC, mewancs approved these changes

2023-11-24 09:53 UTC, ThiwankaB commented
Commit message rules and linting might not be executed during commits. Could you please double-check to ensure that the functionality is working correctly? @sanjayadesilva123321

2023-11-24 09:54 UTC, ThiwankaB requested changes
Commit message rules and linting might not be executed during commits. Could you please double-check to ensure that the functionality is working correctly?

2023-11-24 13:06 UTC, sanjayadesilva123321 commented
> Commit message rules and linting might not be executed during commits. Could you please double-check to ensure that the functionality is working correctly?

Updated

2023-11-27 03:21 UTC, ThiwankaB approved these changes

2023-11-27 03:46 UTC, merged

2023-11-27 03:53 UTC, ThiwankaB commented on README.md
> +## React version
This should be the "NodeJS" version

2023-11-27 03:57 UTC, ThiwankaB commented
If you make alterations after receiving approval on the pull request, please refrain from merging directly. Instead, kindly initiate the review process again, considering the new modifications you've implemented.